spring.application.name=OnlineShop
spring.profiles.active=dev
server.port = 8088

spring.datasource.url=jdbc:postgresql://localhost:5432/onlineshop
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
#spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.forward-headers-strategy=framework

paypal.client-id=AcozPt2fOZlcnj3qM-JIwf1WAmFT7ugPSwyWxNAUJbNhspsXHpOVHlG6J9Or1KE31k2mo98dQBt0FxCU
paypal.client-secret=EKo78w5zvXc6wZTMfajpA1rHMpkH3OYwfuDc5-YkRHFiS5DdRc5HNPgMRnsj6XKhjeLOuAikV_pIXa05
paypal.mode=sandbox

paypal.success-url=http://localhost:8088/mvc/paypal/success
paypal.cancel-url=http://localhost:8088/mvc/paypal/cancel

onlineshop.secret=357638792F423F4428472B4B6250655368566D597133743677397A2443264629