spring.application.name=OnlineShop

server.port = ${PORT:8088}
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://dpg-d90gs5gk1i2s73flt4c0-a.oregon-postgres.render.com:5432/onlineshop_zx4v
spring.datasource.username=onlineshop_zx4v_user
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

paypal.client-id=${PAYPAL_CLIENT_ID}
paypal.client-secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

paypal.success-url=https://onlineshopspringjava.onrender.com/mvc/paypal/success
paypal.cancel-url=https://onlineshopspringjava.onrender.com/mvc/paypal/cancel

onlineshop.secret=${APP_SECRET}