spring.application.name=OnlineShop

server.port = ${PORT:8088}
server.address=0.0.0.0
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

paypal.client-id=${PAYPAL_CLIENT_ID}
paypal.client-secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

paypal.success-url=${PAYPAL_SUCCESS_URL}
paypal.cancel-url=${PAYPAL_CANCEL_URL}

onlineshop.secret=${APP_SECRET}